#!/usr/bin/env php
<?php
require dirname(__DIR__)."/vendor/autoload.php";
$App = \Bot\Application::getInstance();
$api = $App->getApi();
$services = $App->getServices();
$mysqli = $App->getMysqli();

$name = $argv[1];
$className = "Bot\\Tasks\\${name}";
if (class_exists($className)) {
        $Task = new $className($api,  $services, $mysqli);
        if (isset($argv[2])){
            $_function = $argv[2];
            $Task->$_function();
        } else {
            $Task->RUN();
        }
} else {
        echo "Class $className does not exist.";
}
