name: Task Launcher
on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task Name (The task is run only when necessary)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Task ${{ inputs.task }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            become ${{ secrets.NAMETOOL }} bash -c "
              webservice --backend=kubernetes php8.2 shell -- bash -c '/usr/bin/composer --working-dir=/data/project/${{ secrets.NAMETOOL }}/ArWiki install'; 
              webservice --backend=kubernetes php8.2 shell -- bash -c '/data/project/${{ secrets.NAMETOOL }}/ArWiki/src/RunTask ${{ inputs.task }}'"
